---
title: "Lab4_Demo"
author: "Mateo Robbins"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)     # for data wrangling
library(ggplot2)   # for awesome plotting
library(rsample)   # for data splitting
library(caret)     # for logistic regression modeling
library(recipes)
```
Let's explore how employee income and overtime hours affect likelihood of employee attrition.  Any predictions?

```{r}
#
data("attrition", package = "modeldata")

df <- attrition %>% mutate_if(is.ordered, factor, ordered = FALSE)


# Create training (70%) and test (30%) sets for the 
# rsample::attrition data.
set.seed(123)  # for reproducibility (random sample)
churn_split <- initial_split(df, prop = 0.70) # dividing into strata can help with (1) skew and (2) class imbalance
churn_train <- training(churn_split)
churn_test  <- testing(churn_split)
```

```{r recode_attrition_test}
churn_test <- recipe(Attrition ~ ., data = churn_test) |> 
  step_integer(Attrition, zero_based = TRUE) |> 
  prep(churn_test) |> # prep helps us estimate parameters for pre-processing
  bake(churn_test)
```

```{r recode_attrition_train}
churn_train <- recipe(Attrition ~ ., data = churn_train) %>%
  step_integer(Attrition, zero_based = TRUE) %>%
  prep(churn_train) %>%
  bake(churn_train)
```


```{r specify_models_glm}
#MonthlyIncome
model1 <- glm(data = churn_train, Attrition ~ MonthlyIncome, family = binomial)
  
#OverTime
model2 <- glm(data = churn_train, Attrition ~ OverTime, family = binomial)
```


```{r tidy_model_objs}
coef(model1)

coef(model2)

```

```{r exp_coefs}
#exponentiate the coefficients from model objects for interpretation
exp(coef(model1)) # as income goes up by $1, we are actually slightly decreasing the likelihood of leaving the company. this is multiplicative so if goes up again by $1, it's .99*.99 and so on.

exp(coef(model2)) # someone who works overtime is 4 times more likely to quit. since this is binary, it's either yes or no so the yes is 4x more likely to quit than the no. 

```

```{r plot_income_attrition}
 ggplot(churn_test, aes(x=MonthlyIncome, y=Attrition)) + geom_point() +
      stat_smooth(method="glm",  se=TRUE,
                method.args = list(family=binomial))
```



We can add additional predictors, creating a multiple logistic regression model
```{r mult_log_regression}
model3 <- glm(
  Attrition ~ MonthlyIncome + OverTime,
  family = "binomial", 
  data = churn_train
  )

tidy(model3)
```
